# Generated by Django 3.0.5 on 2020-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpro', '0006_auto_20201203_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
    ]
